import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Float, String, Text, text
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class TrainingExample(Base):
    """
    A single (context, analysis) training pair for fine-tuning IntuOne.

    context  — the formatted signal input the model will see
    analysis — the expected intelligence briefing output (the label)

    Sources:
      "synthetic_claude"  — generated by Claude Sonnet (teacher model)
      "human"             — written / validated by a human analyst
      "historical"        — derived from historical resolved markets
    """

    __tablename__ = "training_examples"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    topic: Mapped[str] = mapped_column(String(255), index=True)
    time_window: Mapped[str] = mapped_column(String(20), default="24h")

    # Full formatted prompt context fed to the model
    context: Mapped[str] = mapped_column(Text)
    # Expected model output — the intelligence briefing
    analysis: Mapped[str] = mapped_column(Text)

    # How was this label produced?
    source: Mapped[str] = mapped_column(String(50), default="synthetic_claude")
    # 0.0–1.0 — used for curriculum / quality filtering
    quality_score: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Snapshot of layer scores used to build the context
    layer_breakdown: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    # Signal UUIDs that contributed to this example
    signal_ids: Mapped[list | None] = mapped_column(ARRAY(String), nullable=True)

    is_validated: Mapped[bool] = mapped_column(Boolean, default=False)
    # "train" | "val" | "test"
    split: Mapped[str] = mapped_column(String(10), default="train")
    # Teacher feedback / self-evaluation notes
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=text("now()")
    )
